# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

DESCRIPTION="Comprehensive Perl bindings for OpenSSH"
HOMEPAGE="http://search.cpan.org/search?query=Net-OpenSSH&mode=dist"
SRC_URI="mirror://cpan/authors/id/S/SA/SALVA/${P}.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"

DEPEND="dev-lang/perl"
